CREATE TABLE IF NOT EXISTS `#__trackclubs_trackclub` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `clubname` varchar(256) NOT NULL,
  `published` varchar(256) NOT NULL,
  `user_created` int(11) NOT NULL DEFAULT '0',
  `user_modified` int(11) NOT NULL DEFAULT '0',
  `date_created` DATETIME NOT NULL,
  `date_modified` DATETIME NOT NULL,
  `checked_out` int(11) NOT NULL,
  `checked_out_time` DATETIME NOT NULL,
  PRIMARY KEY  (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS `#__trackclubs_race` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `title` varchar(256) NOT NULL,
  `city` varchar(256) DEFAULT NULL,
  `state` varchar(256) DEFAULT NULL,
  `datetime` datetime NOT NULL,
  `distance` varchar(256) DEFAULT NULL,
  `fees` text,
  `director` varchar(256) DEFAULT NULL,
  `map` text,
  `applicationfilename` varchar(256) DEFAULT NULL,
  `grandprix` tinyint(1) NOT NULL DEFAULT '0',
  `certified` tinyint(1) NOT NULL DEFAULT '0',
  `certifiedmap` varchar(256) DEFAULT NULL,
  `info` text,
  `profile` int(11) NOT NULL DEFAULT '0',
  `terrain` int(11) NOT NULL DEFAULT '0',
  `route` int(11) NOT NULL DEFAULT '0',
  `aid` tinyint(1) NOT NULL DEFAULT '0',
  `prize` tinyint(1) NOT NULL DEFAULT '0',
  `active` tinyint(1) NOT NULL DEFAULT '1',
  `complete` tinyint(1) NOT NULL DEFAULT '0',
  `modifyts` datetime NOT NULL,
  `user_created` int(11) NOT NULL DEFAULT '0',
  `user_modified` int(11) NOT NULL DEFAULT '0',
  `date_created` datetime NOT NULL,
  `date_modified` datetime NOT NULL,
  `checked_out` int(11) NOT NULL,
  `checked_out_time` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=401 ;
CREATE TABLE IF NOT EXISTS `#__trackclubs_result` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `raceid` int(11) NOT NULL DEFAULT '0',
  `athleteid` int(11) NOT NULL DEFAULT '0',
  `time` TIME NOT NULL,
  `dnf` int(11) NOT NULL DEFAULT '0',
  `placeoverride` int(11) NOT NULL DEFAULT '0',
  `timepredecessor` varchar(256) NOT NULL,
  `hidepace` BOOLEAN NOT NULL DEFAULT FALSE,
  `user_created` int(11) NOT NULL DEFAULT '0',
  `user_modified` int(11) NOT NULL DEFAULT '0',
  `date_created` DATETIME NOT NULL,
  `date_modified` DATETIME NOT NULL,
  `checked_out` int(11) NOT NULL,
  `checked_out_time` DATETIME NOT NULL,
  PRIMARY KEY  (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS `#__trackclubs_member` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `lastname` varchar(256) NOT NULL,
  `firstname` varchar(256) NOT NULL,
  `dob` date NOT NULL,
  `gender` varchar(256) NOT NULL,
  `photoid` varchar(256) DEFAULT NULL,
  `active` tinyint(1) NOT NULL DEFAULT '1',
  `expirationdate` date NOT NULL,
  `newmember` tinyint(1) NOT NULL DEFAULT '1',
  `staff` tinyint(1) NOT NULL DEFAULT '1',
  `user_created` int(11) NOT NULL DEFAULT '0',
  `user_modified` int(11) NOT NULL DEFAULT '0',
  `date_created` datetime NOT NULL,
  `date_modified` datetime NOT NULL,
  `checked_out` int(11) NOT NULL,
  `checked_out_time` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1041 ;
CREATE TABLE IF NOT EXISTS `#__trackclubs_athlete` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `firstname` varchar(256) NOT NULL,
  `lastname` varchar(256) NOT NULL,
  `age` int(11) NULL DEFAULT '0',
  `gender` varchar(256) NULL,
  `active` BOOLEAN NOT NULL DEFAULT TRUE,
  `ttcnum` int(11) NULL DEFAULT '0',
  `user_created` int(11) NOT NULL DEFAULT '0',
  `user_modified` int(11) NOT NULL DEFAULT '0',
  `date_created` DATETIME NOT NULL,
  `date_modified` DATETIME NOT NULL,
  `checked_out` int(11) NOT NULL,
  `checked_out_time` DATETIME NOT NULL,
  PRIMARY KEY  (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS `#__trackclubs_grouprun` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `runname` varchar(256) NOT NULL,
  `runday` int(11) NOT NULL DEFAULT '0',
  `runtime` TIME NOT NULL,
  `runlocation` varchar(256) NOT NULL,
  `runaddress` varchar(256) NULL,
  `rundescription` TEXT NOT NULL DEFAULT '',
  `runcontact` varchar(256) NULL,
  `contactemail` varchar(256) NULL,
  `active` BOOLEAN NOT NULL DEFAULT TRUE,
  `user_created` int(11) NOT NULL DEFAULT '0',
  `user_modified` int(11) NOT NULL DEFAULT '0',
  `date_created` DATETIME NOT NULL,
  `date_modified` DATETIME NOT NULL,
  `checked_out` int(11) NOT NULL,
  `checked_out_time` DATETIME NOT NULL,
  PRIMARY KEY  (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS `#__trackclubs_workout` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `title` varchar(256) NOT NULL,
  `owner` int(11) NOT NULL DEFAULT '0',
  `workoutdatetime` varchar(256) NOT NULL,
  `description` TEXT NOT NULL DEFAULT '',
  `user_created` int(11) NOT NULL DEFAULT '0',
  `user_modified` int(11) NOT NULL DEFAULT '0',
  `date_created` DATETIME NOT NULL,
  `date_modified` DATETIME NOT NULL,
  `checked_out` int(11) NOT NULL,
  `checked_out_time` DATETIME NOT NULL,
  PRIMARY KEY  (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS `#__trackclubs_workouttype` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `title` varchar(256) NOT NULL,
  `description` TEXT NOT NULL DEFAULT '',
  `user_created` int(11) NOT NULL DEFAULT '0',
  `user_modified` int(11) NOT NULL DEFAULT '0',
  `date_created` DATETIME NOT NULL,
  `date_modified` DATETIME NOT NULL,
  `checked_out` int(11) NOT NULL,
  `checked_out_time` DATETIME NOT NULL,
  PRIMARY KEY  (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;